---
title: "Interpolate the weight at agecl output to annual age"
author: "Sarah Gaichas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(atlantisom)
library(ggthemes)

```

## Start with saved wrapper weight at age output for NOBA cod

```{r full-test, message=FALSE, warning=FALSE}

source(here("config/NOBA2Config.R"))
NOBAom_cod <- readRDS(file.path(d.name, paste0(scenario.name, "omlist_ss.rds")))

fgs <- NOBAom_cod$funct.group_ss
biolprm <- NOBAom_cod$biol

wtage <- readRDS(file.path(d.name, paste0(scenario.name, "survObsWtAtAge.rds")))
wtage <- wtage[[1]]

wageplot <- ggplot(wtage, aes(time, atoutput)) +
  geom_line(aes(colour = factor(agecl))) +
  theme_tufte() +
  theme(legend.position = "bottom") +
  xlab("model timestep (5 per year)") +
  ylab("average individual weight (g)") +
  labs(subtitle = paste0(scenario.name, " annual mid year sample"))

wageplot + facet_wrap(c("species"), scales="free_y")

```

If we were to do simple interpolation on this output, we can approximate weight at true age class:

```{r interpolate-wtage}
# a function to go into atlantisom, sketched here, reuse calc_stage2age as possible

wtagecl <- wtage
annages <- NOBAom_cod$truenumsage_ss %>%
  group_by(species, time, agecl) %>%
  rename(trueage = agecl) %>%
  summarise(truenatage = sum(atoutput))
  
#calc_wtTrueage <- function(wtagecl, annages, fgs) {
  # get number of ages per agecl from fgs.file
  #fgs <- atlantisom::load_fgs(dir=d.name, file_fgs = functional.groups.file)
  species.code <- fgs$Code
  #turnedon <- fgs[fgs$IsTurnedOn > 0, ]

  # Figure out the groups that have multiple ages classes in each stage (or
  # cohort) this is from the full model
  multiple_ages <- fgs[fgs$NumAgeClassSize>1, c(1,4,10)]
  
  # match species in wtagecl_data to those species in the fgs file
  sppwt <- levels(wtagecl$species)
  multiple_ages <- multiple_ages[multiple_ages$Name %in% sppwt, ]
  
  #now get indices
  names <- multiple_ages$Code
  num_multi_age <- dim(multiple_ages)[1]

  # timesteps from input wt file
  ntimesteps <- length(unique(wtagecl$time))

  # make a dataframe the right dimensions for all age classes
  # has species, time from wtage and trueage, truenatage from annages
  # add agecl column
  # finds the average age of each agecl each timestep based on truenatage
  wtage_out <- annages %>%
    dplyr::semi_join(wtagecl, by = c("species", "time")) %>%
    dplyr::left_join(multiple_ages, by = c("species" = "Name")) %>%
    dplyr::mutate(agecl = as.integer(ceiling(trueage/NumAgeClassSize))) %>%
    dplyr::group_by(species, time, agecl) %>%
    dplyr::mutate(avgage = weighted.mean(trueage, truenatage))
   
  wtage_avgage <- wtage_out %>%
    select(species, time, agecl, avgage) %>%
    distinct()
  
  # find weight increment for a timestep
  # muweight for agecl+1 - muweight for agecl
  wtagecl_inc <- wtagecl %>%
    dplyr::arrange(species, time, agecl) %>%
    #dplyr::left_join(multiple_ages, by = c("species" = "Name")) %>%
    dplyr::group_by(species, time) %>%
    dplyr::mutate(increment = case_when(
      agecl==1 ~ atoutput,
      agecl>1 ~ atoutput - dplyr::lag(atoutput)
      )) %>%
    dplyr::left_join(wtage_avgage) %>%
    dplyr::mutate(avgageinc = case_when(
      agecl==1 ~ avgage,
      agecl>1 ~ avgage - dplyr::lag(avgage)
      )) 
  
  # complex, but works for 2 ages/agecl, need to test more, need to fix oldest
  wtage_out <- wtage_out %>%
    dplyr::select(species, time, trueage, agecl, avgage) %>%
    dplyr::left_join(wtagecl_inc) %>%
    dplyr::group_by(species, time) %>%
    dplyr::mutate(wtIntage = case_when(
      trueage==1 ~ trueage/avgage*increment,
      (trueage>1 & trueage<avgage) ~ 
        (1-(avgage-trueage)/avgageinc)*increment + lag(atoutput),
      (trueage>1 & trueage>avgage) ~ 
        ((trueage-avgage)/lead(avgageinc))*lead(increment) + atoutput
        ))
  

  # plot this--how bad would piecewise linear interpolation be?
  wtageclann <- ggplot(wtagecl_inc, aes(avgage, atoutput)) +
    geom_point() +
    geom_line(aes(colour = factor(time))) + 
    scale_x_continuous(minor_breaks = c(0:20)) +
    theme_tufte() +
    theme(legend.position = "none",
          panel.grid.minor.x = element_line(colour = "grey50"),
          panel.grid.major.x = element_line(colour = "grey50"))
  
  wtageclann + geom_point(data = wtage_out, 
             mapping = aes(trueage, wtIntage))
  # maybe not so bad

  # fix oldest age

  #clean up to have only standard columns
  finaldata <- data.frame("species" = wtage_out$species,
                          "agecl" = wtage_out$trueage, "polygon" = NA, "layer" = NA,
                          "time" = wtage_out$time, "atoutput" = wtage_out$wtIntage)

  # output full set of muweight at newly created agecl

#}
```

Plot interpolated results for more NOBA species:

```{r interp-wtage-test1}


```


