d.name <- here("atlantisoutput","CCconstest")
functional.groups.file <- "CalCurrentV3Groups.csv"
biomass.pools.file <- "DIVCalCurrentV3_Biol.nc"
biol.prm.file <- "CalCurrentV3_Biol.prm"
box.file <- "CalCurrentV3_utm.bgm"
initial.conditions.file <- "DIVCalCurrentV3_Biol.nc"
run.prm.file <- "CalCurrentV3_run.xml"
scenario.name <- "outputCCV3"
bioind.file <- "outputCCV3BiomIndx.txt"
catch.file <- "outputCCV3Catch.txt"
annage <- FALSE
fisheries.file <- "CalCurrentV3Fisheries.csv"
