---
title: "Poseidon Adventure"
output: html_document
---

 <!-- ADD LINKS BELOW, note, using the RMD link syntax will open the presentation in the same tab, which is annoying. Use the html with the "_blank" to fix that behavior -->

These pages document initial testing of the atlantisom package in development at https://github.com/r4atlantis/atlantisom using three different [Atlantis](https://research.csiro.au/atlantis/) output datasets. Development of atlantisom began at the [2015 Atlantis Summit](https://research.csiro.au/atlantis/atlantis-summit/) in Honolulu, Hawaii, USA. 

<a href="https://sgaichas.github.io/poseidon-dev/atlantisom_landingpage.html" target="_blank">Draft atlantisom landing page for review, June 9, 2020</a>

### Diagnosing diet and consumption outputs, May 2021

<a href="https://sgaichas.github.io/poseidon-dev/PerCapitaConsumption.html" target="_blank"> Compare NOBA and CCA consumption outputs, June 15, 2021</a>

### Full age structured data for multispecies modeling, June-December 2020

Code converting these outputs to multispecies production model and length structured model inputs is in development as of spring 2021 and is on the [ms-keyrun repository](https://github.com/NOAA-EDAB/ms-keyrun/blob/master/docs/SimData.Rmd). See also <a href="https://noaa-edab.github.io/ms-keyrun/SimData.html" target="_blank"> Initial simulated data, May 24, 2021</a>

<a href="https://sgaichas.github.io/poseidon-dev/SurveyDietCompTest.html" target="_blank">Apply survey specifications to diet outputs, December 7, 2020</a>

<a href="https://sgaichas.github.io/poseidon-dev/msSurveysTest.html" target="_blank">Compare multispecies survey specifications, November 9, 2020</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBAmsdiets.html" target="_blank">Explore NOBA diet comps and multi-survey multispecies wrappers, October 21, 2020</a>

Including detailed diet exploration, multiple surveys, survey function bug fixes for species with < 10 cohorts.


### Full age structured dataset for Norwegian Barents cod, March-June 2020

<a href="https://sgaichas.github.io/poseidon-dev/NOBAcod.html" target="_blank">Apply and extend wrappers to get full age structure, updated June 5, 2020</a>

<a href="https://sgaichas.github.io/poseidon-dev/InterpolateWeightAtAge.html" target="_blank">Interpolate to get average weight at true age, June 5, 2020</a>

Also bug fixed config files for multispecies dataset. Interpolate wtage includes data generation for NOBA cod (max age 20), redfish (max age 40), and capelin (max age 5).

### Working on wrapper functions, January 2020

<a href="https://sgaichas.github.io/poseidon-dev/WrapperDevelopment.html" target="_blank">Automating om functions to streamline workflows, January 17, 2020 writes dat file as of March 16, 2020</a>

### Visualize functions for documentation

<a href="https://sgaichas.github.io/poseidon-dev/Visualize_atlantisom.html" target="_blank">Different packages to visualize `atlantisom` functions, updated June 15, 2020</a>

### Demo for NEMoW meeting, December 2019

<a href="https://sgaichas.github.io/poseidon-dev/Sardines_atlantisom2SS_demo.html" target="_blank">Sardines in the CalCurrent run with F, rec dev, and climate scenario, all true and SS data, runs SS3, November 21, 2019</a>


### An example workflow for a single species (in progress)

<a href="https://sgaichas.github.io/poseidon-dev/FullSardineTruthEx.html" target="_blank">Sardines in the CalCurrent, all true data, May 22, 2019, updated May 23, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CreateStockSynthesis.html" target="_blank">Sardines in the CalCurrent, input to SS functions: May 24, 2019</a> - now generalized to run for any species in the cal current with a unique species config file

May 24: Sardines have a full dataset, but still working on converting to true ages for species with multiple ages per age class. See below under [True age compositions]. 

<a href="https://sgaichas.github.io/poseidon-dev/SardinesOnlyatlantisom2SStest.html" target="_blank">Sardines in the CalCurrent run with F and rec dev scenario, all true and SS data, May 31, 2019, updated June 7</a>

The below generates a readable dat file for input into SS3 for sardines. The control file and biological parameters still need hand modification, but SS3 now runs.

<a href="https://sgaichas.github.io/poseidon-dev/SardinesHakeatlantisom2SStest.html" target="_blank">Sardines in the CalCurrent run with F, rec dev, and climate scenario, all true and SS data, October 1, 2019</a>

So we can start some comparisons of true and model estimated attributes.

<a href="https://sgaichas.github.io/poseidon-dev/SkillAssessInit.html" target="_blank">Compare Atlantis truth with SS3 estimated B, R, and F, October 1, 2019</a>


### Read this first on overall workflow

<a href="https://sgaichas.github.io/poseidon-dev/RethinkSamplingFunctions.html" target="_blank">Big picture and new functions needed - May 10, 2019, updated May 16, 2019</a>

May 11: Changes to `atlantisom::sample_fish` and new `atlantisom::aggregateDensityData` functions seem to work. See below under [Length compositions].

May 15: Changes to `atlantisom::calc_age2length` to allow user specified max length bin seem to work. Also listed under [Length compositions].

May 20-22: Fisheries, corrections to nums at age for Cal Current and decision to read in the catch.txt file for total catch in weight

### Testing the atlantisom code

<a href="https://sgaichas.github.io/poseidon-dev/TrueBioTest.html" target="_blank">Installation and initial tests - April 26, 2019, updated April 30, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NEUSExamples.html" target="_blank">Survey census visualization for NEUS -  April 30, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCAExamples.html" target="_blank">Survey census visualization for CCA - April 30, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBAExamples.html" target="_blank">Survey census visualization for NOBA - April 30, 2019</a>

### Create a standard survey

<a href="https://sgaichas.github.io/poseidon-dev/StandardSurveyTest.html" target="_blank">Initial survey tests - April 30, 2019, updated May 1, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NEUSStandardSurveyTest.html" target="_blank">Standard survey visualization for NEUS -  May 1, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCAStandardSurveyTest.html" target="_blank">Standard survey visualization for CCA - May 1, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBAStandardSurveyTest.html" target="_blank">Standard survey visualization for NOBA - May 1, 2019</a>

### Start age composition sampling: by output age class, not true age

<a href="https://sgaichas.github.io/poseidon-dev/TrueLengthAgeCompTest.html" target="_blank">Initial age comp tests - May 2, 2019, updated May 6, 2019</a>

CCA outputs had some 0 length at age, requiring changes to `atlantisom::sample_fish`

<a href="https://sgaichas.github.io/poseidon-dev/NEUSTrueLengthAgeCompTest.html" target="_blank">True and sample fish census comparison NEUS - May 6, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCATrueLengthAgeCompTest.html" target="_blank">True and sample fish census comparison CCA - May 6, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBATrueLengthAgeCompTest.html" target="_blank">True and sample fish census comparison NOBA - May 6, 2019</a>

Standard survey with composition sampling: impact of selectivity, `sample_fish`

<a href="https://sgaichas.github.io/poseidon-dev/StdSurvLengthAgeCompTest.html" target="_blank">Compare true cohort comp with survey + sampling - May 6, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NEUSStdSurvCohortCompTest.html" target="_blank">True cohort comp vs survey comparison NEUS - May 6, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCAStdSurvCohortCompTest.html" target="_blank">True cohort comp vs survey comparison CCA - May 6, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBAStdSurvCohortCompTest.html" target="_blank">True cohort comp vs survey comparison NOBA - May 6, 2019</a>

### Length compositions

Difficult when you don't have a good idea of the outputs you are using!

<a href="https://sgaichas.github.io/poseidon-dev/TrueLengthCompTest_fail.html" target="_blank">Defeated by length compositions - May 8-9, 2019</a>

Better when you do:

<a href="https://sgaichas.github.io/poseidon-dev/TrueLengthCompTest.html" target="_blank">Victory: length compositions - May 11, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCATrueLengthCompTest.html" target="_blank">CCA length composition examples - May 11, 2019</a>

But don't try running length comps at the subannual level for all species.

<a href="https://sgaichas.github.io/poseidon-dev/NOBATrueLengthCompTest.html" target="_blank">NOBA length composition examples - May 13, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NEUSTrueLengthCompTest.html" target="_blank">NEUS length composition examples - May 13, 2019</a>

Standard survey with length sampling: impact of selectivity, `sample_fish`

<a href="https://sgaichas.github.io/poseidon-dev/StdSurvLengthCompTest.html" target="_blank">Compare survey + sampled lengths with true - May 14, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/CCAStdSurvLengthCompTest.html" target="_blank">CCA compare survey + sampled lengths with true - May 14, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NOBAStdSurvLengthCompTest.html" target="_blank">NOBA compare survey + sampled lengths with true - May 15, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/NEUSStdSurvLengthCompTest.html" target="_blank">NEUS compare survey + sampled lengths with true - May 15, 2019</a>

Test new user specified max length bin for a large species:

<a href="https://sgaichas.github.io/poseidon-dev/TestBiggerMaxLen.html" target="_blank">Default 150 cm, try different max - May 15, 2019</a>

Do we see ever small fish for large species? Is this normal, or a problem with length estimation?

<a href="https://sgaichas.github.io/poseidon-dev/TestSmallestLength.html" target="_blank">Are length comps OK on the small end? - May 15, 2019</a>

May 16: Isaac says CCA fish look reasonable. NOBA Greenland halibut growth parameterization was reportedly "a nightmare" with conflicting science and datasets, so maybe we don't worry too much about them right now.

### Weight at age: by output age class, how to get to true age basis?

<a href="https://sgaichas.github.io/poseidon-dev/TestWeightAtStage.html" target="_blank">How much variability in weight at stage? - May 16, 2019</a>

Work in progress on interpolating weight at age in InterpolateWeightAtAge.Rmd

### Testing a full workflow through fisheries (sardine, agecl = true age)

<a href="https://sgaichas.github.io/poseidon-dev/Atlantisom2SSworkflowtest.html" target="_blank">Try for true datasets new CC model with climate - May 21, 2019, updated May 22, 2019 with catch correction</a>

Fishery catch problem, older codebase has a bug in output. Test with NOBA...

<a href="https://sgaichas.github.io/poseidon-dev/TestCatchNOBA.html" target="_blank">Suggests a workaround needed for catch in weight - May 21, 2019</a>

### True age compositions

<a href="https://sgaichas.github.io/poseidon-dev/FullBoccaccioTruthEx.html" target="_blank">Initial testing of true age functions, now running but output still wrong - May 24, 2019, updated May 27, 2019</a>

<a href="https://sgaichas.github.io/poseidon-dev/TestCalcZ.html" target="_blank">Test Z calc and compare with true annage NOBA - May 24, 2019</a>

May 24: Either `calc_Z` or `calc_stage2age` or both are incorrect if we expect them to exactly match atlantis annual age ouput where it is available. We match in timestep 0, then diverge. May 27 update: also true for Bocaccio in CCA, the interim numbers at age drop to 0.

June 7: `calc_Z` seems incorrect when compared to outputMort.txt; stepping through code needed

June 11: fixed matching of recruitment to timestep, still seems off

June 13: I think we have the best `calc_Z` we are going to get. After discussion with Beth, we should not expect to match output of Mort.txt because M gets rescaled so much. However, the comparison looks reasonable now for sardine and even for NOBA cod.

<a href="https://sgaichas.github.io/poseidon-dev/TestCalcZ2.html" target="_blank">Test Z calc and compare with output mort CCA and NOBA - June 7, 2019, updated June 13 and December 11 with M</a>

Dec 11: Our calculated Z is less than the input F. Does Atlantis rescale F?

June 14: fixed a bug and `calc_stage2age` works better now that it is using Z, and now that Zs are in the right ballpark. Still not a perfect match to true age output.

<a href="https://sgaichas.github.io/poseidon-dev/TestCalcStage2AgeNOBA.html" target="_blank">Test stage to age calculations and compare true age output NOBA - June 14, 2019</a>

June 15: while the age splitting is functioning better, applying it to a species with more than 2 ages per age class (CC Bocaccio rockfish) shows that our application of an annual Z estimate may not be the best approach. The functions themselves could use further tweaking.

Overall it is advisable to use true age output from more recent Atlantis codebases where possible.

<a href="https://sgaichas.github.io/poseidon-dev/FullBoccaccioTruthEx2.html" target="_blank">Redo Bocaccio test with CCA F scenario, June 15, 2019</a>

Further experiments with M, F, and Z across models and species confirm that mortality needs a lot more work: 

<a href="https://sgaichas.github.io/poseidon-dev/TestCalcFandM.html" target="_blank">Why is mortality all over the map? June 12, 2020</a>


### Rabbit holes that turned out ok

<a href="https://sgaichas.github.io/poseidon-dev/CheckBiomassAges.html" target="_blank">In which I broke the very first thing that worked, then fixed it - June 4, 2019</a>

### More to come later!
